### ISSUE TITLE
Can I Contribute logo for retrofit-kaiteki ?

### ISSUE THREAD

**Issue by iqbalhood** [kroegerama/retrofit-kaiteki#1]
Hello @kroegerama, Can I Contribute to make Logo For This Project ?

**Comment by kroegerama** [comment]
@iqbalhood Yes, sure! That would be awesome!

**Comment by iqbalhood** [comment]
Hello @kroegerama ,
These are my logo proposal for your application. If there any revision, please just tell it.

![asset 1hdpi](https://user-images.githubusercontent.com/1563756/42227446-c0a8def2-7f0b-11e8-8ef1-fb2a8d9b9bc2.png)

**Comment by kroegerama** [comment]
Looks great, @iqbalhood 
Thanks a lot! I will add it to the readme, if you provide me a png version :)

**Comment by iqbalhood** [comment]
Hello Sir. Thanks for choosing my logo. You can get the PNG and Editable file here 
https://drive.google.com/drive/folders/1Z3bZZ9y2dUVSUWSQgnDmEFRBAuUp9Qae?usp=sharing

**Comment by iqbalhood** [comment]
Hello Sir, I have made some modification on the logo for better presentation.

![logo](https://user-images.githubusercontent.com/1563756/42408178-7eebd76e-81f2-11e8-960b-dd3eba7dacd1.png)

And make pull request here.
https://github.com/kroegerama/retrofit-kaiteki/pull/3
I Hope it can be merged soon , 
If you have some revission please just tell it to me :)
Thank's :)

**Comment by kroegerama** [comment]
Thanks a lot! The logo is now included :)
